### PR TITLE
Replaced window by global reference available also in node

### PR DESCRIPTION
**Pull request by martinpucala**
window is only present in browser and root points to it (as this points to window in global context in browser), so this makes it work with node again. cheers

### CODE REVIEW

**Comment by namniak** [comment]
It's not going to work then with browserify. as root won't be 'window/ so all this HDPI stuff would be ignored. Try 'npm t' on retina to see the result.

**Comment by martinpucala** [comment]
Ok, I see. Will try to do fix it in some other way, let me get back asap

**Comment by namniak** [comment]
Thanks a lot!

**Comment by martinpucala** [comment]
Hoho, I see you were faster :) Now it works for me both in browser and with node-canvas on backend! Good work, thank you :)

**Comment by namniak** [comment]
Cool.  I didn't really consider backend at all so thanks a lot for your help and your interest!

**Pull request merged**
